# MF Baseline Configuration
learning_rate: 0.005
embedding_size: 16
train_batch_size: 2048

# Dataset Settings for pre-split
benchmark_filename: ['train', 'valid', 'test']
load_col:
    inter: [user_id, item_id, rating, timestamp, intervene_mask]
eval_args:
    mode: full
    order: RO
    split: {'RS': [0.8, 0.1, 0.1]} # This is ignored when benchmark_filename is used but good for completeness
    group_by: user

eval_neg_sample_args:
    distribution: uniform
    sample_num: 1
